CREATE TABLE [dbo].[table3] (
	[table3_id] INT IDENTITY (1000, 1) NOT FOR REPLICATION NOT NULL,
	[table1_id] INT NOT NULL,
	[data] VARCHAR(1000) NULL,
	[modified_date] DATETIME2(7) NOT NULL,
	CONSTRAINT [pk_table3] PRIMARY KEY CLUSTERED (table1_id),
	CONSTRAINT [CK_table3] CHECK NOT FOR REPLICATION (data IS NOT NULL)
)

GO